# -*- coding: utf-8 -*-
"""Model_4.1_EfficientNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgpCUhZN1UIbGTunQtErBlHOEfntc9po
"""

!ls /content

from google.colab import drive
drive.mount('/content/drive')

import zipfile
import os

# CHANGE 1: Update this zip path to your own file in Drive
zip_path = '/content/drive/MyDrive/Colab Notebooks/ham10000.zip'

# CHANGE 2: Local extraction folder in Colab
extract_path = '/content/ham10000_data'
os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extracted to:", extract_path)

import tensorflow as tf
print(tf.__version__)

!pip install -q tensorflow scikit-learn seaborn scipy pillow

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
from glob import glob
from PIL import Image

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import class_weight
from sklearn.metrics import classification_report, confusion_matrix

import seaborn as sns
from scipy import stats

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import models
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.applications.efficientnet import preprocess_input


from sklearn.utils import resample

print("All imports done")

"""# Reading the CSV file"""

skin_df = pd.read_csv(os.path.join(extract_path, 'HAM10000_metadata.csv'))

print(skin_df.head())

print(skin_df.tail())

print("\nDisease types:", skin_df['dx'].unique())  # Listing the unique diseases. Expected output: classes = 7

"""# Label encoding to convert text labels to numbers"""

le = LabelEncoder()
skin_df['label'] = le.fit_transform(skin_df['dx'])

# To show the mapping
print("Class labels:")
for i, name in enumerate(le.classes_):
    print("{} -> {}".format(i,name))

print(skin_df.sample(10))

skin_df.head()

"""# Data visualization using plots"""

fig = plt.figure(figsize=(12, 8))

# ----- Plot 1: Plotting the disease types (or Cell Types) -------
ax1 = fig.add_subplot(221)
skin_df['dx'].value_counts().plot(kind='bar', ax=ax1)
ax1.set_ylabel('Count')
ax1.set_title('Cell Type')

# ------ Plot 2: Plotting to see the distribution of gender -----
ax2 = fig.add_subplot(222)
skin_df['sex'].value_counts().plot(kind='bar', ax=ax2)
ax2.set_ylabel('Count')
ax2.set_title('Sex')

# --- Plot 3: Plotting localization -------
ax3 = fig.add_subplot(223)
skin_df['localization'].value_counts().plot(kind='bar', ax=ax3)
ax3.set_ylabel('Count')
ax3.set_title('Localization')

# ----- Plot 4: Age Distribution ------
ax4 = fig.add_subplot(224)

#sample_age = skin_df[pd.notnull(skin_df['age'])]
age_data = skin_df['age'].dropna()

# Using histogram + KDE for better visualization of whether the data is symmetric or skewed
sns.histplot(age_data, kde=True, stat='density', color='red', ax=ax4)

# Displaing the fitted normal curve
mean, std_dev = stats.norm.fit(age_data)
xmin, xmax = ax4.get_xlim()
x = np.linspace(xmin, xmax, 100)
p = stats.norm.pdf(x, mean, std_dev)

ax4.plot(x, p, linewidth=2, color = 'blue')      # the normal curve
ax4.set_title('Age Distribution')
ax4.set_xlabel('age')
ax4.set_ylabel('Density')

plt.tight_layout()
plt.show()

"""In the age distribution curve, we see that our data is not following the normal curve (which is blue in colour). Hence we, can infer that it is not symmetric

# Visualising the distribution of data into various classes
"""

print(type(skin_df))

print(skin_df.shape)

print(skin_df['label'].value_counts())

"""**From the graph and the values here, we can infer that the data is imbalanced.**

# Reading all image paths (all .jpg files in both of the image folders)
"""

image_path = {
    os.path.splitext(os.path.basename(x))[0]: x
    for x in glob(os.path.join('ham10000_data/HAM10000_images_part_*', '*.jpg'))
}

# Adding a new column named 'path' to the dataframe
skin_df['path'] = skin_df['image_id'].map(image_path.get)

# Now, we drop the rows where image was not found
skin_df = skin_df.dropna(subset=['path'])

print(f"Total images available: {len(skin_df)}")

skin_df.info()

"""Therefore, we can see that all rows have an image. In other words, there are no rows without one.

# The following shows the number of images for each disease
"""

print(skin_df['dx'].value_counts())

"""Again we can see that there is some imbalance."""

# Ploting a bar chart
plt.figure(figsize=(10, 5))
skin_df['dx'].value_counts().plot(kind='bar', color='skyblue', edgecolor='black')
plt.title("Number of Images per Skin Disease")
plt.ylabel("Count")
plt.xlabel("Disease")
plt.xticks(rotation=45)
plt.grid()
plt.show()

"""# Spliting the data into 70% for training and 15% for validation and 15% for testing"""

X_paths = skin_df['path'].values
Y = skin_df['label'].values

X_train_val_paths, X_test_paths, y_train_val_labels, y_test_labels = train_test_split(
    X_paths, Y, test_size=0.15, random_state=42, stratify=Y
)

X_train_paths, X_val_paths, y_train_labels, y_val_labels = train_test_split(
    X_train_val_paths, y_train_val_labels, test_size=0.1765, random_state=42, stratify=y_train_val_labels
)

print("\nTrain samples:", len(X_train_paths))
print("Validation samples:", len(X_val_paths))
print("Test samples:", len(X_test_paths))

"""# Now, below we compute the class weights

Since the data is skewed, we try to compute the class weights such that the rare classes get more weightage than the common ones.
"""

class_weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train_labels),
    y=y_train_labels
)
class_weight_dict = dict(enumerate(class_weights))

print("Class weights:", class_weight_dict)

"""## Data Augmentation"""

SIZE = 224
BATCH_SIZE = 16

train_data_gen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    zoom_range=0.2,
    shear_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

val_test_data_gen = ImageDataGenerator(preprocessing_function=preprocess_input)

train_df = pd.DataFrame({
    'path': X_train_paths,
    'label': y_train_labels.astype(str)
})

val_df = pd.DataFrame({
    'path': X_val_paths,
    'label': y_val_labels.astype(str)
})

test_df = pd.DataFrame({
    'path': X_test_paths,
    'label': y_test_labels.astype(str)
})

train_generator = train_data_gen.flow_from_dataframe(
    dataframe=train_df,
    x_col='path',
    y_col='label',
    target_size=(SIZE, SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=True
)

val_generator = val_test_data_gen.flow_from_dataframe(
    dataframe=val_df,
    x_col='path',
    y_col='label',
    target_size=(SIZE, SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

test_generator = val_test_data_gen.flow_from_dataframe(
    dataframe=test_df,
    x_col='path',
    y_col='label',
    target_size=(SIZE, SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

"""# Now, we build the EfficientNet model"""

base_model = EfficientNetB0(
    weights='imagenet',
    include_top=False,
    input_shape=(SIZE, SIZE, 3)
)

base_model.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.3)(x)
predictions = Dense(7, activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=predictions)

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

"""# We now set the callbacks"""

callbacks = [
    ReduceLROnPlateau(monitor='val_accuracy', factor=0.5, patience=3, verbose=1),
    EarlyStopping(monitor='val_accuracy', patience=7, restore_best_weights=True)
]

"""### Explanation for myself:

The **ReduceLROnPlateau** monitors our model's accuracy on validation data i.e., *monitor='val_accuracy'*. If this accuracy doesnot improve for like 3 epochs in a row, since *patience=3*, it reduces the learning rate into half, since *factor=0.5*.

The **EarlyStopping** also watches the *val_accuracy*. and if that doesnot get better for 7 consecutive epochs, since *patience=7*, it completely stops the training. This then loads the model's best weights from earlier, since we do: *restore_best_weights=True*, so we donot have to end up with an overfitted or even a worse version.

## Model Training
"""

history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=25,
    class_weight=class_weight_dict,
    callbacks=callbacks,
    verbose=1
)

"""# We finally plot the resuts"""

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

"""# Test evaluation"""

score = model.evaluate(test_generator, verbose=0)
print("Test Loss:", score[0])
print("Test Accuracy:", score[1])

y_pred = model.predict(test_generator)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = test_generator.classes

cm = confusion_matrix(y_true, y_pred_classes)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=le.classes_,
            yticklabels=le.classes_)
plt.title("Confusion Matrix")
plt.xlabel("Predicted Disease")
plt.ylabel("True Disease")
plt.show()

print("\nClassification Report:")
print(classification_report(y_true, y_pred_classes, target_names=le.classes_))